### ISSUE TITLE
Wrong work with non-latin characters in paths

### ISSUE THREAD

**Issue by AlexRozen** [thomas694/finddupe#2]
Hello! I have found, that there is a big problems with paths, that contain non-latin characters. 
Checked that trough console switched to different codepages, even 65001 (UTF8)

I attached sample zip archive with such folder structure.
Wrong work sample (with some strange error messages):
`S:\>finddupe .\Test\**\*.dll .\Test\**\*.xml .\Test\**\*.тест`
`Error: No files matched '.\Test\**\*.xml'Code.AvalonEdit.dll`
`Error: No files matched '.\Test\**\*.????'`
`Files:      592 kBytes in     1 files`
`Dupes:        0 kBytes in     0 files`

After renaming the folders to latin-only characters:

`S:\>finddupe .\Test\**\*.dll .\Test\**\*.xml`
`Duplicate: '.\Test\Test 1\ICSharpCode.AvalonEdit.dll'`
`With:      '.\Test\Test 2\ICSharpCode.AvalonEdit.dll'`
`Duplicate: '.\Test\Test 2\nunit.framework.dll'`
`With:      '.\Test\Test 3\nunit.framework.dll'`
`Duplicate: '.\Test\Test 1\ICSharpCode.AvalonEdit.xml'`
`With:      '.\Test\Test 2\ICSharpCode.AvalonEdit.xml'`
`Duplicate: '.\Test\Test 2\nunit.framework.xml'`
`With:      '.\Test\Test 3\nunit.framework.xml'`

[Test.zip](https://github.com/thomas694/finddupe/files/13601976/Test.zip)

P.S. Also I want to mention, that in some locations default console codepage (OEM) is distinct from current default Windows codepage (ANSI). For example in my country the default Windows codepage is 1251, but the default console codepage is 866.

**Comment by thomas694** [comment]
Hello,
thanks for reporting a bug and providing the good analysis and test data.

The error is solved in the new version.

**Comment by AlexRozen** [comment]
Thank you for fast response! 
Strange error messages seems to be gone, but it still doesn't process the non-latin paths :(
I have tried this commands after chcp 866, chcp1251 and chcp65001:

`
S:\9\Test>dir /s /b
S:\9\Test\Тест 1
S:\9\Test\Тест 2
S:\9\Test\Тест 3
S:\9\Test\Тест 1\ICSharpCode.AvalonEdit.dll
S:\9\Test\Тест 1\ICSharpCode.AvalonEdit.xml
S:\9\Test\Тест 2\ICSharpCode.AvalonEdit.dll
S:\9\Test\Тест 2\ICSharpCode.AvalonEdit.xml
S:\9\Test\Тест 2\nunit.framework.dll
S:\9\Test\Тест 2\nunit.framework.xml
S:\9\Test\Тест 3\nunit.framework.dll
S:\9\Test\Тест 3\nunit.framework.xml

S:\9\Test>finddupe .\Test\**\*.dll .\Test\**\*.xml .\Test\**\*.тест 
Error: No files matched '.\Test\**\*.dll'
Error: No files matched '.\Test\**\*.xml'
Error: No files matched '.\Test\**\*.тест'
No files to process
`

**Comment by AlexRozen** [comment]
Thank you for your great work! Fix is working like a charm!

**Comment by AlexRozen** [comment]
Sorry, but there are still problems in my environment. 
Seems, than non-ascii paths still can't be used as arguments of finddupe.exe :(

P.S. just tested on Windows Server 2016.

**Comment by thomas694** [comment]
Can you please describe it more? So it works under normal Windows, but not under Windows Server? I cannot test with Windows Server here.
Which options resp. command line are you using?

**Comment by AlexRozen** [comment]
> Which options resp. command line are you using?
```
C:\_CMD\1>finddupe.exe ".\Test\Тест 1\*.*" ".\Test\Тест 2\*.*" ".\Test\Тест 3\*.*"
Error: No files matched '.\Test\???? 2\*.*'de.AvalonEdit.dll
Error: No files matched '.\Test\???? 3\*.*'

Files:      592 kBytes in     1 files
Dupes:        0 kBytes in     0 files
``` 
checked after chcp 866 and chcp 65001

then:
```
C:\_CMD\1>cd .\Test

C:\_CMD\1\Test>..\finddupe.exe .\

Files:      592 kBytes in     1 files
Dupes:        0 kBytes in     0 files
```

**Comment by thomas694** [comment]
Well, are you sure you tested it with the new exe?
Someone else also tested it on Win Server 2016 and it showed four duplicates, but the automatic code page change didn't work.
But I have no idea why the automatic doesn't work there.

**Comment by AlexRozen** [comment]
> Well, are you sure you tested it with the new exe?

File version is 1.31.0.0

**Comment by AlexRozen** [comment]
On Windows 10:
```
S:\9\Test>finddupe.exe  ".\**\*.dll"  ".\**\*.xml"
Duplicate: '.\Тест 1\ICSharpCode.AvalonEdit.dll'
With:      '.\Тест 2\ICSharpCode.AvalonEdit.dll'
Duplicate: '.\Тест 2\nunit.framework.dll'
With:      '.\Тест 3\nunit.framework.dll'
Duplicate: '.\Тест 1\ICSharpCode.AvalonEdit.xml'
With:      '.\Тест 2\ICSharpCode.AvalonEdit.xml'
Duplicate: '.\Тест 2\nunit.framework.xml'
With:      '.\Тест 3\nunit.framework.xml'
Files:     3633 kBytes in     8 files                                                                                                                                                                                                                                             Dupes:     1816 kBytes in     4 files         
``` 

On Windows 10 after changing the console mode to legacy:
```
S:\9\Test>finddupe.exe  ".\**\*.dll"  ".\**\*.xml"
Duplicate: '.\ТWith:      '.\ТDuplicate: '.\ТWith:      '.\ТDuplicate: '.\ТWith:      '.\ТDuplicate: '.\ТWith:      '.\Т
Files:     3633 kBytes in     8 files
Dupes:     1816 kBytes in     4 files

```

**Comment by thomas694** [comment]
Thanks, that could be a good hint. But at least in this case, it's only a visual problem.

**Comment by thomas694** [comment]
The Legacy Console mode "has extremely rudimentary and often incorrect support of UTF-8 with code page 65001".

Is the console of your Server 2016 also running in Legacy Mode?

**Comment by AlexRozen** [comment]
> Is the console of your Server 2016 also running in Legacy Mode?

Seems to be not:
[https://learn.microsoft.com/en-us/windows-server/administration/windows-console-changes](url)
(There is a separate setting for console apps to be run in legacy mode)

I repeated my tests in freshly installed Windows Server 2016 under Hyper-V with all actual updates and without activating the legacy console mode. Things are still the same :(

P.S. It seems that switching current codepage to 65001 from inside the app is not a good idea. There is a lot of console apps which are working with national non-ASCII characters from console without any issues. For example 7zip, which is open-sourced.

**Comment by AlexRozen** [comment]
By the way, Happy New Year!

**Comment by thomas694** [comment]
> By the way, Happy New Year!

Thanks, the same to you!

**Comment by thomas694** [comment]
Please check [this version](https://ci.appveyor.com/api/buildjobs/ememf8is1dxivbkg/artifacts/Release%2Ffinddupe.exe), if it works for you.

**Comment by AlexRozen** [comment]
> Please check [this version](https://ci.appveyor.com/api/buildjobs/ememf8is1dxivbkg/artifacts/Release%2Ffinddupe.exe), if it works for you.

Brief check shows that it seems to be working!

```
C:\1\Test>..\finddupe.exe -hardlink "Тест 1" "Тест 2" "Тест 3"
Duplicate: 'Тест 1\ICSharpCode.AvalonEdit.dll'
With:      'Тест 2\ICSharpCode.AvalonEdit.dll'
    (hardlinked instances of same file)
Duplicate: 'Тест 1\ICSharpCode.AvalonEdit.xml'
With:      'Тест 2\ICSharpCode.AvalonEdit.xml'
    (hardlinked instances of same file)
Duplicate: 'Тест 2\nunit.framework.dll'
With:      'Тест 3\nunit.framework.dll'
    Created hardlink
Duplicate: 'Тест 2\файло.framework.xml'
With:      'Тест 3\nunit.framework.xml'
    Created hardlink

Files:     3633 kBytes in     8 files
Dupes:      718 kBytes in     2 files

C:\1\Test>..\finddupe.exe -hardlink "Тест 1" "Тест 2" "Тест 3"
Duplicate: 'Тест 1\ICSharpCode.AvalonEdit.dll'
With:      'Тест 2\ICSharpCode.AvalonEdit.dll'
    (hardlinked instances of same file)
Duplicate: 'Тест 1\ICSharpCode.AvalonEdit.xml'
With:      'Тест 2\ICSharpCode.AvalonEdit.xml'
    (hardlinked instances of same file)
Duplicate: 'Тест 2\nunit.framework.dll'
With:      'Тест 3\nunit.framework.dll'
    (hardlinked instances of same file)
Duplicate: 'Тест 2\файло.framework.xml'
With:      'Тест 3\nunit.framework.xml'
    (hardlinked instances of same file)

Files:     3633 kBytes in     8 files
Dupes:        0 kBytes in     0 files
``` 

The only found trouble -- there is badly crash when start the app without any given command line arguments.

**Comment by thomas694** [comment]
A new version has been released.
